[general]
import = ["~/.config/alacritty/rose-pine-dawn.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "none"
opacity = 0.8

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
size = 14.0

[colors]
cursor = { text="#faf4ed", cursor = "#d7827e"}
